version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    target-branch: master
    reviewers:
      - nadnoslen
    labels:
      - dependencies
    ignore:
      - dependency-name: ember-cli
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: ember-data
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: ember-source
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
